[cite_start]name: Flujo_trabajo_Token # [cite: 678]

on:
  push:
    branches:
      - [cite_start]main # Se activa al subir cambios a main [cite: 681, 683]

jobs:
  validar-auth:
    [cite_start]runs-on: ubuntu-latest # [cite: 690]
    steps:
      - name: Checkout code
        [cite_start]uses: actions/checkout@v3 # Clona el c√≥digo en el servidor [cite: 694, 695]

      - name: Use Personal Access Token
        # Realiza una llamada a la API de GitHub usando tu secreto guardado [cite: 731, 734]
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/user/repos # [cite: 734, 735, 736]